version: '3.1'
services:
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./hosts:/etc/nginx/conf.d
            - ./www/:/var/www
            - ./logs:/var/log/nginx
        networks:
            - app-network
    php:
        build: ./images/php
        container_name: php-fpm
        volumes:
            - ./www:/var/www
        environment:
            PHP_IDE_CONFIG: ${PHP_IDE_CONFIG}
        networks:
            - app-network
    db:
        image: mysql:5.7
        container_name: db
        restart: unless-stopped
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        volumes:
            - ./db:/var/lib/mysql
        networks:
            - app-network
    adminer:
        image: adminer:latest
        restart: unless-stopped
        ports:
            - 8080:8080
        networks:
            - app-network
networks:
        app-network:
            driver: bridge